- name: Deploy Application to Kubernetes
  hosts: k8s_master
  become: yes
  tasks:
    - name: Ensure kubectl is installed
      apt:
        name: kubectl
        state: present
        update_cache: yes

    - name: Ensure kubernetes Python module is installed
      pip:
        name: kubernetes
        state: present
        executable: pip3

    - name: Deploy Application on Kubernetes Master
      k8s:
        state: present
        definition: |
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: health-care
          spec:
            replicas: 2
            selector:
              matchLabels:
                app: health-care
            template:
              metadata:
                labels:
                  app: health-care
              spec:
                containers:
                - name: health-care
                  image: indu1919/health-care:v1
                  ports:
                  - containerPort: 8081

    - name: Expose the Deployment
      k8s:
        state: present
        definition: |
          apiVersion: v1
          kind: Service
          metadata:
            name: health-care-service
          spec:
            selector:
              app: health-care
            ports:
              - protocol: TCP
                port: 8085
                targetPort: 8081
            type: NodePort

- name: Deploy Application to Kubernetes Workers
  hosts: k8s_worker
  become: yes
  tasks:
    - name: Ensure kubectl is installed
      apt:
        name: kubectl
        state: present
        update_cache: yes

    - name: Ensure kubernetes Python module is installed
      pip:
        name: kubernetes
        state: present
        executable: pip3
