- name: Ensure required packages are installed
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  loop:
    - python3-pip
    - kubectl

- name: Install kubernetes Python module
  pip:
    name: kubernetes
    executable: pip3
    state: present

- name: Deploy Application on Kubernetes Cluster
  k8s:
    state: present
    definition: |
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: health-care
      spec:
        replicas: 2
        selector:
          matchLabels:
            app: health-care
        template:
          metadata:
            labels:
              app: health-care
          spec:
            containers:
              - name: health-care
                image: indu1919/health-care:v1
                ports:
                  - containerPort: 8081

- name: Expose the Deployment
  k8s:
    state: present
    definition: |
      apiVersion: v1
      kind: Service
      metadata:
        name: health-care-service
      spec:
        selector:
          app: health-care
        ports:
          - protocol: TCP
            port: 8085
            targetPort: 8081
        type: NodePort
