- name: Deploy Health-Care Application on Kubernetes
  hosts: all
  become: yes
  tasks:
    - name: Check if kubectl is installed
      command: kubectl version --client
      register: kubectl_check
      ignore_errors: yes

    - name: Fetch deployment.yaml from GitHub
      fetch:
        src: https://raw.githubusercontent.com/indusharma19/health-care/master/ansible/deployment.yaml
        dest: /tmp/health-care/ansible/deployment.yaml
        flat: yes

    - name: Fetch service.yaml from GitHub
      fetch:
        src: https://raw.githubusercontent.com/indusharma19/health-care/master/ansible/service.yaml
        dest: /tmp/health-care/ansible/service.yaml
        flat: yes

    - name: Deploy Health-Care Deployment
      command: kubectl apply -f deployment.yaml
      args:
        chdir: /tmp/health-care/ansible

    - name: Expose Health-Care Service
      command: kubectl apply -f service.yaml
      args:
        chdir: /tmp/health-care/ansible
