- name: Deploy Health-Care Application on Kubernetes
  hosts: all
  become: yes
  tasks:
    - name: Check if kubectl is installed
      command: kubectl version --client
      register: kubectl_check
      ignore_errors: yes

    - name: Deploy Health-Care Deployment
      command: kubectl apply -f deployment.yaml
      args:
        chdir: /tmp/health-care/ansible  # Adjust the path if necessary

    - name: Expose Health-Care Service
      command: kubectl apply -f service.yaml
      args:
        chdir: /tmp/health-care/ansible  # Adjust the path if necessary
