- name: Deploy Health-Care Application on Kubernetes
  hosts: all
  become: yes
  tasks:
    - name: Check if kubectl is installed
      command: kubectl version --client
      register: kubectl_check
      ignore_errors: yes

    - name: Clone GitHub repository
      git:
        repo: https://github.com/indusharma19/health-care.git
        dest: /tmp/health-care
        version: master

    - name: Deploy Health-Care Application
      command: kubectl apply -f deployment.yaml -f service.yaml
      args:
        chdir: /tmp/health-care/ansible  # Adjust the path if necessary
